version: '3'
services: 
  apirest:
    build:
      dockerfile: Dockerfile
      context: ./apiRest
    volumes: 
      - ./apiRest/api:/app/api
      - ./apiRest/package.json:/app/package.json
    #ports: 
    #  - "3001:3001"
  site:
    stdin_open: true
    build: 
      dockerfile: Dockerfile
      context: ./site
    volumes: 
      - ./site/public:/app/public
      - ./site/src:/app/src
      - ./site/views:/app/views
      - ./site/package.json:/app/package.json
    #ports: 
    #  - "80:3000"
  nginx:
    depends_on: 
      - site
      - apirest
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "8080:80"